summary: ''
value:
  fullscreen: false
  grid:
    - '12':
        fixed: true
        fullHeight: false
        h: 2
        w: 12
        x: 0
        'y': 0
      '3':
        fixed: true
        fullHeight: false
        h: 2
        w: 6
        x: 0
        'y': 0
      id: topbar
      data:
        id: topbar
        type: containercomponent
        configuration: {}
        customCss:
          container:
            class: '!p-0'
            style: ''
        numberOfSubgrids: 1
    - '12':
        fixed: false
        fullHeight: false
        h: 1
        w: 2
        x: 0
        'y': 2
      '3':
        fixed: false
        fullHeight: false
        h: 1
        w: 1
        x: 0
        'y': 2
      id: a
      data:
        id: a
        type: buttoncomponent
        componentInput:
          type: runnable
          autoRefresh: false
          fields:
            x:
              type: static
              value: null
              fieldType: string
          fieldType: any
          recomputeOnInputChanged: false
          runnable:
            name: Inline Script
            inlineScript:
              content: '!inline inline_script.inline_script.py'
              lock: '!inline inline_script.inline_script.lock'
              language: python3
              path: u/admin/newapp/Inline_Script
              schema:
                $schema: 'https://json-schema.org/draft/2020-12/schema'
                type: object
                properties:
                  x:
                    type: string
                    description: ''
                    default: null
                    originalType: string
                required:
                  - x
        configuration:
          afterIcon:
            type: static
          beforeIcon:
            type: static
          color:
            type: static
            value: blue
          confirmationModal:
            type: oneOf
            configuration:
              none: {}
            selected: none
          disabled:
            type: static
            value: false
          fillContainer:
            type: static
            value: false
          label:
            type: static
            value: Press me
          onError:
            type: oneOf
            configuration:
              errorOverlay: {}
            selected: errorOverlay
          onSubmit:
            type: oneOf
            configuration:
              none: {}
            selected: none
          onSuccess:
            type: oneOf
            configuration:
              none: {}
            selected: none
          runInBackground:
            type: static
            value: false
          size:
            type: static
            value: xs
          tooltip:
            type: static
            value: ''
          triggerOnAppLoad:
            type: static
            value: false
        customCss:
          button:
            class: ''
            style: ''
          container:
            class: ''
            style: ''
        horizontalAlignment: center
        recomputeIds: []
        verticalAlignment: center
  hiddenInlineScripts: []
  hideLegacyTopBar: true
  mobileViewOnSmallerScreens: false
  subgrids:
    topbar-0:
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 0
          'y': 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 0
          'y': 0
        id: title
        data:
          id: title
          type: textcomponent
          componentInput:
            type: templatev2
            connections:
              - id: summary
                componentId: ctx
            eval: '${ctx.summary}'
            fieldType: template
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: true
              fieldType: boolean
            style:
              type: static
              value: Body
            tooltip:
              type: evalv2
              value: ''
              connections:
                - id: author
                  componentId: ctx
              expr: '`Author: ${ctx.author}`'
              fieldType: text
          customCss:
            container:
              class: ''
              style: ''
            text:
              class: text-xl font-semibold whitespace-nowrap truncate
              style: ''
          horizontalAlignment: left
          verticalAlignment: center
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 6
          'y': 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 3
          x: 0
          'y': 1
        id: recomputeall
        data:
          id: recomputeall
          type: recomputeallcomponent
          configuration:
            defaultRefreshInterval:
              type: static
              value: '0'
          customCss:
            container:
              class: ''
              style: ''
          horizontalAlignment: right
          menuItems: []
          verticalAlignment: center
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
